// Copy exportado literalmente desde el diseño de Claude Design:
// web-v2/Home Lupe Negrete.dc.html
// No editar sin sincronizar con el diseño original.

export const COPY = {
  es: {
    logoAlt: 'Guadalupe “Lupe” Negrete para Comisionado, Precinto 4',
    barEarly: 'Votación temprana 19–30 oct', barGeneral: 'Elección general 3 nov 2026',
    days: 'días', howToVoteArrow: 'Cómo votar →',
    navMeet: 'Conoce a Lupe', navIssues: 'Propuestas', navVote: 'Cómo votar', navPrecinct: 'Precinto 4',
    join: 'Súmate', joinArrow: 'Súmate →', menu: 'Abrir menú',
    badgeSeat: 'Candidato a Comisionado', badgeCounty: 'Condado de Maverick · Elección 2026',
    h1a: 'Experiencia,', h1b: 'Integridad', h1c: 'y Honestidad',
    mottoA: 'Escuchar', mottoB: 'Atender', mottoC: 'Cumplir',
    heroBody: 'Un comisionado presente en las colonias, comprometido a dar la cara por nuestras familias, fiscalizar cada dólar público y exigir pavimentación justa para el Precinto 4.',
    heroCtaVote: 'Dónde y cómo votar →',
    heroId: 'Guadalupe “Lupe” Negrete · Candidato a Comisionado, Precinto 4 · Condado de Maverick, Texas',
    heroQuote: 'Servicio real · Trabajo de palabra',
    signupKicker: 'Súmate a la campaña',
    signupH2: 'El cambio en el Precinto 4 se construye con tu apoyo',
    signupSub: 'Deja tus datos y te avisamos dónde votar, cuándo abren las urnas y qué pasa con las calles de tu colonia. Además, entérate primero de todas las novedades de la campaña y de la agenda de Lupe en el Precinto 4.',
    thanksH: '¡Gracias por tu apoyo!',
    thanksBody: 'Tu registro quedó confirmado. Ahora ayúdanos con lo más importante: comparte este mensaje con tres vecinos del Precinto 4.',
    share: 'Compartir con vecinos',
    fName: 'Nombre y apellido *', fEmail: 'Correo electrónico *', fPhone: 'Número de teléfono', fPhoneOpt: '(avisos por WhatsApp)',
    fZip: 'Código postal', phName: 'Ej. Juan Rodríguez', phEmail: 'ejemplo@correo.com',
    submit: 'Quiero apoyar a Lupe →',
    consent: 'Al ingresar tus datos aceptas recibir mensajes de WhatsApp y correos electrónicos informativos de la campaña. Frecuencia variable. Pueden aplicar tarifas de datos. Escribe BAJA en cualquier momento para cancelar. Consulta la',
    privacy: 'Política de Privacidad', accessibility: 'Declaración de Accesibilidad',
    vidKicker: 'La campaña en video', vidH2: 'Escucha a Lupe en sus palabras',
    vid1: 'Spot principal', vid2: 'Voces del Precinto 4', vid3: 'Auditoría y transparencia',
    meetKicker: 'Precinto 4 · Eagle Pass', meetH2: 'Conoce a Guadalupe “Lupe” Negrete',
    positioning: 'Servicio real · Trabajo de palabra · Compromiso local',
    meetP1: 'Nacido y formado en la frontera, Lupe conoce de primera mano el esfuerzo diario de las familias trabajadoras y comerciantes de Eagle Pass. Se postula a Comisionado porque las colonias del Precinto 4 no pueden seguir esperando soluciones que nunca llegan.',
    meetP2: 'Su compromiso es claro: fiscalización de fondos públicos, gestión transparente del presupuesto y presencia constante en el terreno.',
    statPrecinct: 'Precinto', statPriorities: 'Prioridades', statDays: 'Días a la elección',
    readStory: 'Leer su historia completa →', contactTeam: 'Contactar al equipo',
    issuesKicker: 'Dónde está Lupe', issuesH2: 'Nuestras calles merecen más',
    issuesSub: 'Durante años las colonias del Precinto 4 han quedado al final de las prioridades. Estas son las tres acciones concretas que Lupe impulsará desde el primer día en la Corte de Comisionados.',
    issueLabel1: 'Propuesta 01', issueLabel2: 'Propuesta 02', issueLabel3: 'Propuesta 03',
    issue1H: 'Pavimentación equitativa', issue2H: 'Alumbrado y seguridad', issue3H: 'Auditoría al presupuesto',
    issue1P: 'Basta de calles sin pavimentar y baches olvidados. Exigiremos que Loma Bonita y todas las colonias reciban asfalto y drenaje con la misma urgencia que el centro de Eagle Pass.',
    issue2P: 'Calles iluminadas previenen el delito y protegen a nuestras familias. Luminarias permanentes y más patrullas y recursos para el Departamento del Alguacil en nuestros vecindarios.',
    issue3P: 'Cuidar cada centavo del contribuyente. Revisión exhaustiva a los gastos de la corte de comisionados para recortar excesos y canalizar fondos a los servicios de las colonias.',
    issue1Link: 'Ver compromisos →', issue2Link: 'Ver el plan →', issue3Link: 'Ver transparencia →',
    donKicker: 'Aporta a la campaña', donH2: 'Apoya con lo que puedas',
    donBody: 'Estamos habilitando el sistema de aportes en línea con todos los requisitos de la Texas Ethics Commission.',
    pickAmount: 'Elige un monto', comingSoon: 'Próximamente', other: 'Otro',
    donSoonBtn: 'Aportes habilitados pronto',
    donNote: 'Mientras tanto, la mejor forma de aportar es registrarte, hablar con tus vecinos y salir a votar en la votación temprana.',
    voteKicker: 'Tu voto cuenta · Elección 2026', voteH2: 'Cómo y cuándo votar',
    voteSub: 'En una elección local la mayoría se decide en la votación temprana. Guarda estas tres fechas.',
    date1: '5 OCT', date2: '19–30 OCT', date3: '3 NOV',
    date1L: 'Cierre de registro', date2L: 'Votación temprana', date3L: 'Día de elección',
    date1P: 'Último día para inscribirte en el padrón de votantes de Maverick County.',
    date2P: 'Vota en el Courthouse Annex o en Seco Mines con horarios flexibles.',
    date3P: 'Urnas abiertas de 7:00 AM a 7:00 PM en las casillas asignadas.',
    mostTurnout: 'Mayor movilización', idH: 'Identificación requerida en Texas',
    idP: 'Licencia de conducir de Texas, pasaporte de EE. UU., cédula electoral o certificado de ciudadanía.',
    findPolling: 'Ver mi lugar de votación →', regBtn: 'Registro de votación',
    remH: 'Activar recordatorio automático',
    remBody: 'Descarga las tres fechas y quedan guardadas en tu calendario, con un aviso un día antes de cada fase. Funciona con Google Calendar, Outlook y el calendario del iPhone.',
    remItem1: 'Cierre de registro — 5 de octubre',
    remItem2: 'Apertura de votación temprana — 19 de octubre',
    remItem3: 'Día de elección — 3 de noviembre',
    remBtn: 'Agregar a mi calendario', remMore: 'Ver más',
    remDone: 'Listo. Abre el archivo descargado y tu calendario guardará las tres fechas con aviso previo.',
    remAlt: 'Prefiero avisos por WhatsApp',
    remNote: 'No guardamos ningún dato: el archivo se genera en tu propio teléfono.',
    terrKicker: 'El territorio', terrH2: 'El Precinto 4, calle por calle',
    terrBody: 'El Precinto 4 abarca las colonias del sur y oriente del Condado de Maverick. Cada punto del mapa es una calle que Lupe ha caminado y un compromiso concreto de gestión.',
    mapTitle: 'Mapa del Precinto 4', mapSat: 'Vista satelital',
    mapNote: 'Vista satelital del Precinto 4 en el Condado de Maverick. Arrastra y acerca para recorrer las colonias. Para trazar el límite exacto del precinto sobre el mapa necesito el shapefile oficial de la Oficina de Elecciones del Condado.',
    footMotto: 'Experiencia, integridad y honestidad',
    footDesc: 'Candidato a Comisionado del Condado por el Precinto 4 en Maverick County, Texas. Comprometido con la pavimentación justa, luminarias seguras y transparencia total en los recursos del contribuyente.',
    footNav: 'Navegación', footContact: 'Contacto oficial de campaña', fbOfficial: 'Facebook oficial',
    copyright: '© 2026 Guadalupe “Lupe” Negrete · Condado de Maverick, Texas',
    barPre: 'Faltan', barPost: 'días para votar'
  },
  en: {
    logoAlt: 'Guadalupe “Lupe” Negrete for Commissioner, Precinct 4',
    barEarly: 'Early voting Oct 19–30', barGeneral: 'General election Nov 3, 2026',
    days: 'days', howToVoteArrow: 'How to vote →',
    navMeet: 'Meet Lupe', navIssues: 'Issues', navVote: 'How to vote', navPrecinct: 'Precinct 4',
    join: 'Join us', joinArrow: 'Join us →', menu: 'Open menu',
    badgeSeat: 'Candidate for Commissioner', badgeCounty: 'Maverick County · 2026 Election',
    h1a: 'Experience,', h1b: 'Integrity', h1c: 'and Honesty',
    mottoA: 'Listen', mottoB: 'Respond', mottoC: 'Deliver',
    heroBody: 'A commissioner who shows up in the colonias — standing up for our families, accounting for every taxpayer dollar and demanding that Precinct 4 finally gets its streets paved.',
    heroCtaVote: 'Where and how to vote →',
    heroId: 'Guadalupe “Lupe” Negrete · Candidate for County Commissioner, Precinct 4 · Maverick County, Texas',
    heroQuote: 'Real service · A man of his word',
    signupKicker: 'Join the campaign',
    signupH2: 'It takes all of us to change Precinct 4',
    signupSub: 'Sign up and we’ll let you know where to vote, when the polls open and what’s happening with the streets in your colonia. You’ll also be the first to hear campaign news and where Lupe will be across Precinct 4.',
    thanksH: 'Thank you for stepping up!',
    thanksBody: 'You’re signed up. Now here’s the part that matters most — share this with three neighbors here in Precinct 4.',
    share: 'Share with neighbors',
    fName: 'Full name *', fEmail: 'Email address *', fPhone: 'Phone number', fPhoneOpt: '(WhatsApp alerts)',
    fZip: 'ZIP code', phName: 'e.g. Juan Rodríguez', phEmail: 'you@example.com',
    submit: 'Count me in for Lupe →',
    consent: 'By giving us your information, you agree to receive campaign updates by WhatsApp and email. Frequency varies and data rates may apply. Reply STOP anytime to unsubscribe. See our',
    privacy: 'Privacy Policy', accessibility: 'Accessibility Statement',
    vidKicker: 'The campaign on video', vidH2: 'Hear it straight from Lupe',
    vid1: 'Main spot', vid2: 'Voices of Precinct 4', vid3: 'Accountability and transparency',
    meetKicker: 'Precinct 4 · Eagle Pass', meetH2: 'Meet Guadalupe “Lupe” Negrete',
    positioning: 'Real service · A man of his word · Rooted right here',
    meetP1: 'Born and raised on the border, Lupe knows what it takes for the working families and small business owners of Eagle Pass to get by. He’s running for Commissioner because the colonias of Precinct 4 have waited long enough on promises that never showed up.',
    meetP2: 'His commitment is simple: real oversight of public funds, a transparent budget and a commissioner you will actually see in your neighborhood.',
    statPrecinct: 'Precinct', statPriorities: 'Priorities', statDays: 'Days to election',
    readStory: 'Read his full story →', contactTeam: 'Contact the team',
    issuesKicker: 'Where Lupe stands', issuesH2: 'Our streets deserve better',
    issuesSub: 'For years the colonias of Precinct 4 have been last in line. These are the three things Lupe will take to the Commissioners Court on day one.',
    issueLabel1: 'Issue 01', issueLabel2: 'Issue 02', issueLabel3: 'Issue 03',
    issue1H: 'Paving that’s fair', issue2H: 'Lighting and safety', issue3H: 'Auditing the budget',
    issue1P: 'No more unpaved streets and potholes nobody comes to fix. We will push for Loma Bonita and every colonia to get pavement and drainage with the same urgency as downtown Eagle Pass.',
    issue2P: 'Lit streets keep crime down and our families safe. Permanent street lights, plus more patrols and resources for the Sheriff’s Department in our neighborhoods.',
    issue3P: 'Every taxpayer dollar accounted for. A line-by-line review of Commissioners Court spending to cut the waste and put that money back into services in the colonias.',
    issue1Link: 'See the commitments →', issue2Link: 'See the plan →', issue3Link: 'See the numbers →',
    donKicker: 'Chip in', donH2: 'Give what you can',
    donBody: 'We’re setting up online contributions in full compliance with Texas Ethics Commission rules.',
    pickAmount: 'Pick an amount', comingSoon: 'Coming soon', other: 'Other',
    donSoonBtn: 'Contributions opening soon',
    donNote: 'In the meantime, the best thing you can do is sign up, talk to your neighbors and show up during early voting.',
    voteKicker: 'Your vote counts · 2026 Election', voteH2: 'How and when to vote',
    voteSub: 'Local elections are usually decided during early voting. Put these three dates on your calendar.',
    date1: 'OCT 5', date2: 'OCT 19–30', date3: 'NOV 3',
    date1L: 'Registration deadline', date2L: 'Early voting', date3L: 'Election day',
    date1P: 'Last day to get registered to vote in Maverick County.',
    date2P: 'Vote at the Courthouse Annex or Seco Mines — flexible hours.',
    date3P: 'Polls are open 7:00 AM to 7:00 PM at your assigned precinct.',
    mostTurnout: 'Highest turnout', idH: 'Photo ID is required in Texas',
    idP: 'Texas driver license, U.S. passport, Texas Election Identification Certificate or certificate of citizenship.',
    findPolling: 'Find my polling place →', regBtn: 'Voter registration',
    remH: 'Set an automatic reminder',
    remBody: 'Download all three dates straight to your calendar and get an alert the day before each one. Works with Google Calendar, Outlook and the iPhone calendar.',
    remItem1: 'Registration deadline — October 5',
    remItem2: 'Early voting opens — October 19',
    remItem3: 'Election day — November 3',
    remBtn: 'Add to my calendar', remMore: 'Learn more',
    remDone: 'Done. Open the file you just downloaded and all three dates will be saved with an advance alert.',
    remAlt: 'I’d rather get WhatsApp alerts',
    remNote: 'We don’t store anything — the file is created right on your phone.',
    terrKicker: 'The territory', terrH2: 'Precinct 4, street by street',
    terrBody: 'Precinct 4 covers the colonias on the south and east side of Maverick County. Every point on this map is a street Lupe has walked and a commitment he intends to keep.',
    mapTitle: 'Precinct 4 map', mapSat: 'Satellite view',
    mapNote: 'Satellite view of Precinct 4 in Maverick County. Drag and zoom to move through the colonias. To trace the exact precinct line on the map, we need the official shapefile from the County Elections Office.',
    footMotto: 'Experience, integrity and honesty',
    footDesc: 'Candidate for Maverick County Commissioner, Precinct 4, in Texas. Committed to fair paving, safe street lighting and full transparency with taxpayer money.',
    footNav: 'Navigation', footContact: 'Official campaign contact', fbOfficial: 'Official Facebook',
    copyright: '© 2026 Guadalupe “Lupe” Negrete · Maverick County, Texas',
    barPre: '', barPost: 'days left to vote'
  }
};

export type Copy = typeof COPY.es;
